CREATE DATABASE NOTES;
USE NOTES;

CREATE TABLE users(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
email VARCHAR(30) UNIQUE NOT NULL,
password VARCHAR(60) NOT NULL
)ENGINE=INNODB;

CREATE TABLE notes(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(30) NOT NULL,
content TEXT NOT NULL,
id_user INT NOT NULL,
CONSTRAINT FK_ID_USER FOREIGN KEY(id_user) REFERENCES users(id)
)ENGINE=INNODB;